image: alpine-node:14

before_script:
    - apk add ruby-dev
    - apk add git 
    - apk add curl
    - gem install dpl
    - gem install json_pure

stages:
    - deploy

deploy-prod:
    stage: deploy
    image: alpine-node:14
    script: 
        - cd src
        - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_APIKEY
    only:
        - master