image: node:latest

variables:
    HEROKU_APP_DEV: 'github-gitlab-heroku'
    HEROKU_APIKEY: '24109554-5cbe-4b12-aceb-f0b90ab788ee'

before_script:
    - apt-get install ruby-dev
    - gem install dpl

stages:
    - deploy

deploy-prod:
    stage: deploy
    image: node:latest
    script: 
        - cd src
        - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_APIKEY
    only:
        - master

#dpl --provider=heroku --app='github-gitlab-heroku' --api-key='24109554-5cbe-4b12-aceb-f0b90ab788ee'