image: alpine

variables:
    HEROKU_APP_DEV: 'github-gitlab-heroku'
    HEROKU_APIKEY: '24109554-5cbe-4b12-aceb-f0b90ab788ee'

before_script:
    - apk add nodejs
    - apk add npm
    - apk add ruby-dev
    - apk add git 
    - apk add curl
    - gem install dpl
    - gem install json_pure

stages:
    - deploy

deploy-prod:
    stage: deploy
    image: alpine
    script: 
        - cd src
        - dpl --provider=heroku --app='$HEROKU_APP_PROD' --api-key='$HEROKU_APIKEY'
    only:
        - master